export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_ERROR = 'GET_COURSES_ERROR';

export const GET_QUEUE_REQUEST = 'GET_QUEUE_REQUEST';
export const GET_QUEUE_SUCCESS = 'GET_QUEUE_SUCCESS';
export const GET_QUEUE_ERROR = 'GET_QUEUE_ERROR';

export const POST_CALL_REQUEST = 'POST_CALL_REQUEST';
export const POST_CALL_SUCCESS = 'POST_CALL_SUCCESS';
export const POST_CALL_ERROR = 'POST_CALL_ERROR';

export const DELETE_CALL_REQUEST = 'DELETE_CALL_REQUEST';
export const DELETE_CALL_SUCCESS = 'DELETE_CALL_SUCCESS';
export const DELETE_CALL_ERROR = 'DELETE_CALL_ERROR';

export const SELECT_COURSE = 'SELECT_COURSE';
export const SET_USER_DATA = 'SET_USER_DATA';